make plugin compatible with webpack2
fabiandev/split-by-path-webpack-plugin pull request #1
Opened 2017-01-05 11:29 UTC by TitanNano

This fixes the API changes between webpack 1 and 2.

2017-01-05 23:18 UTC, fabiandev requested changes
Please don't change the version number in the `package.json` in a pull request.

2017-01-05 23:21 UTC, fabiandev commented
Will this break compatibility with older webpack versions, or was `chunk.hasRuntime()` already available before webpack 2?

2017-01-20 12:11 UTC, TitanNano commented
@fabiandev okay I fixed the version number as requested. The entry point also needs to be updated or the resulting bundle won't work. 

Yes `chunk.hasRuntime()` did not exist in Webpack 1, therefore this will break the compatibility with Webpack 1.

2017-01-20 13:30 UTC, fabiandev approved these changes

2017-01-20 13:31 UTC, merged